version: '3.5'
services:
  guitar-shop.uploader.mongo:
    image: mongo
    restart: always
    container_name: guitar-shop.uploader.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: guitar-shop-uploader

    ports:
      - '27018:27017'

    volumes:
      - guitar-shop.mongo.uploader:/data/db

    networks:
      - guitar-shop.uploader

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/guitar-shop-uploader --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  guitar-shop.uploader.mongo.ui:
    image: mongo-express
    restart: always
    container_name: guitar-shop.uploader.mongo.ui
    ports:
      - '8083:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@guitar-shop.uploader.mongo:27017/

    networks:
      - guitar-shop.uploader
volumes:
  guitar-shop.mongo.uploader:

networks:
  guitar-shop.uploader:
      driver: bridge
